-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwfzZNdPYZJozPsz0
BEXvWZ6Y6C8gp0DO54GU6hZ1xPehRANCAAQl60BSIqnRqb9mHvgVOsoUbhhwSgJD
wLjboMma7BxAns5JQ2ouCPre40KPTF2ChAWjXq+ZfFDegxRweS4lSj+f
-----END PRIVATE KEY-----